// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrblsogcfnlxqnwmxclz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyYmxzb2djZm5seHFud214Y2x6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzNDA2NzcsImV4cCI6MjA1MzkxNjY3N30.UnwEUfIj1JyOqLm3t4t5kpEHN8s2qboxrbviaQCAggM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);